version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'env_zucchetti'
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
        - "8989:80"
    volumes:
        - ./:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
        - laravel

  postgresql:
    image: bitnami/postgresql
    restart: unless-stopped
    environment:
        POSTGRESQL_USERNAME: ${DB_USERNAME:-username}
        POSTGRESQL_PASSWORD: ${DB_PASSWORD:-userpass}
        POSTGRESQL_DATABASE: ${DB_DATABASE:-laravel}
    volumes:
        - ./docker/postgres:/var/lib/postgresql/data
    ports:
        - "5433:5432"
    networks:
        - laravel

  redis:
    image: redis:latest
    networks:
      - laravel

networks:
  laravel:
    driver: bridge